name: PizzaUtils
main: dev.pizzasmp.utils.PizzaUtils
version: 1.0.0
api-version: "1.21.6"
author: PizzaSMP
description: Lightweight ping utility.
commands:
  ping:
    description: Show your current ping.
    usage: /ping
    permission: pizzasmp.ping
permissions:
  pizzasmp.ping:
    description: View your ping.
    default: true
