blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/FolksyPizza/SMP-Core/security/advisories/new
    about: Report security problems privately.
